/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_ewohltman_Leaky */

#ifndef _Included_com_github_ewohltman_Leaky
#define _Included_com_github_ewohltman_Leaky
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_ewohltman_Leaky
 * Method:    leak
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_ewohltman_Leaky_leak
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
